name = "tabit-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

# Environment variables are set via dashboard or CLI
# Use: wrangler secret put <NAME>

[env.production]
name = "tabit-worker"

[env.staging]
name = "tabit-worker-staging"

# Routes match all paths
# To restrict, use: routes = [{ pattern = "/api/*", zone_name = "example.com" }]
